# Basics

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.2.0'

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [5]:
x= torch.from_numpy(arr)
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [7]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

In [10]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [11]:
torch.tensor([1.5,2.6,4.9],dtype=torch.int16)

tensor([1, 2, 4], dtype=torch.int16)

In [12]:
torch.empty(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
x = torch.linspace(0,18,12).reshape(3,4)
x

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [15]:
x.device

device(type='cpu')

In [17]:
x=torch.arange(0,100)
print(x)
x.view(10,10)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
x.view(20,-1) # baki shob gulake size korbe

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]])

In [22]:
x.view(-1,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]])

In [23]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
a*b

tensor([ 4, 10, 18])

In [24]:
torch.dot(a,b)

tensor(32)

In [25]:
a.dot(b)

tensor(32)

In [31]:
torch.mm(a.view(1,-1),b.view(-1,1))

tensor([[32]])

In [29]:
b.view(-1,1)

tensor([[4],
        [5],
        [6]])

In [32]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [33]:
a

tensor([[0., 2., 4.],
        [1., 3., 5.]])

In [34]:
b

tensor([[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [35]:
torch.mm(a,b)

tensor([[56., 62.],
        [80., 89.]])

In [36]:
a.mm(b)

tensor([[56., 62.],
        [80., 89.]])

In [41]:
a= torch.tensor([3,4],dtype=float)

In [42]:
a.norm() # sqrt(3**2+4**2)

tensor(5., dtype=torch.float64)

In [44]:
x = torch.ones(3,7)
x[0][0]=0

In [45]:
x

tensor([[0., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [46]:
x.numel()

21

In [47]:
x

tensor([[0., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [48]:
x.type(torch.int16)

tensor([[0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]], dtype=torch.int16)

# Gradient

#### one

In [1]:
import torch
import numpy
x = torch.tensor([2],dtype=torch.float32,requires_grad=True)
y= 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)
y.backward()

tensor([63.], grad_fn=<AddBackward0>)


![title](img/tmp.png)

In [2]:
x.grad

tensor([93.])

#### two

In [6]:
x = torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True)
y= 2*x**4 + x**3 + 3*x**2 + 5*x + 1
z1 = y.sum()
z1.backward()
z1

tensor(307., grad_fn=<SumBackward0>)

In [7]:
x.grad

tensor([ 22.,  93., 266.])

*this is actually individual gradient for each of x=1,x=2,x=3*
![title](img/3.png)

#### three

In [8]:
x = torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True)
y= 2*x**4 + x**3 + 3*x**2 + 5*x + 1
z2 = y.mean()
z2.backward()
z2

tensor(102.3333, grad_fn=<MeanBackward0>)

In [9]:
x.grad

tensor([ 7.3333, 31.0000, 88.6667])

*this is actually individual gradient/3 for each of x=1,x=2,x=3*
![title](img/4.png)

#### four

In [13]:
x = torch.tensor([1,2,3],dtype=torch.float64,requires_grad=True)
y=x**2-1
z=y**2-5*y+6
out = z.sum()
out.backward()
out

tensor(36., dtype=torch.float64, grad_fn=<SumBackward0>)

In [14]:
x.grad

tensor([-10.,   4.,  66.], dtype=torch.float64)

In [16]:
(36*2+24)/3

32.0